### ISSUE TITLE
[Spike] Investigate Wagtail CMS

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-team#29]
### Background
We would like to explore the feasibility of using the [Wagtail CMS ](https://wagtail.org/) for implementing the Design System. 

### Tasks
- [ ] Create a sandbox
- [ ] PoC: create a page using the Service Manual e.g. a bulletin page
- [ ] Test integrity and identify any issues

Acceptance Criteria
- [ ] A PoC to share with the team 
- [ ] Any issues identified and documented
